version: '3.8'

services:
  backend:
    build: .
    container_name: utech_trivia_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # O comando abaixo recarrega o código em tempo real no container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
